name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Quote version to preserve string and avoid YAML float parsing
        go-version: ["1.20"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build (non-Windows)
        if: matrix.os != 'windows-latest'
        run: go build -o md2docx ./cmd/md2docx

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: go build -o md2docx.exe ./cmd/md2docx
      - name: Run tests
        run: go test ./...