name: Release
permissions:
  contents: write

on:
  push:
    # Trigger on version tags
    tags:
      - 'v*.*.*'
  # Allow manual triggering of release workflow
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # Quote version to preserve string and avoid YAML float parsing
          go-version: "1.20"
      - name: Build binaries
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          TARGETS=("linux_amd64" "windows_amd64" "darwin_amd64")
          for target in "${TARGETS[@]}"; do
            os=${target%%_*}
            arch=${target##*_}
            ext=""
            if [ "$os" = "windows" ]; then ext=".exe"; fi
            GOOS=$os GOARCH=$arch go build -o md2docx_${VERSION}_${os}_${arch}${ext} ./cmd/md2docx
          done
      - name: Package binaries
        run: |
          mkdir -p release
          for bin in md2docx_*; do
            zip -j "release/${bin}.zip" "$bin"
          done
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          # Use the pushed tag name
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        uses: actions/setup-gh-cli@v2

      - name: Upload Release Assets
        run: |
          gh release upload ${{ github.ref_name }} release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}